name: Build Curiso App
on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: bun install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_MASTER_KEY: ${{ secrets.VITE_MASTER_KEY }}
          VITE_FALLBACK_KEY: ${{ secrets.VITE_FALLBACK_KEY }}
        with:
          tagName: v__VERSION__
          releaseName: 'Curiso AI v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false